env:
  es2021: true
  node: true
  jest: true

extends: airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-unused-vars: warn
  no-console: off
  no-underscore-dangle: off
  no-shadow: off
  import/extensions:
    - error
    - ignorePackages
    - js: always
