name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # necesario si usas OIDC
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      # Ejecutar tests y generar cobertura lcov
      - run: npm test -- --coverage --coverageReporters=lcov

      # Subir cobertura a Qlty Cloud usando OIDC
      - name: Upload coverage to Qlty Cloud
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage/lcov.info
